ONTOLOGY_NAME: atomistic
ONTOLOGY_PREFIX: at
ONTOLOGY_IRI: https://w3id.org/emmo/domain/atomistic
BUILD_DIR: build
GIT_REPOSITORY: emmo-repo/domain-atomistic
GIT_BASE_URL: github.com
REFERENCE_SUBSECTIONS: all
REFERENCE_IMPORTED: 'false'
REFERENCE_RECURSIVE: 'true'
REFERENCE_IRI_REGEX: https://w3id.org/emmo/domain/atomistic#

REFERENCE_INDICES:
- ontology_file: build/atomistic.ttl
  title: Properties Index
  docfile: properties.rst
  iri_regex: https://w3id.org/emmo/domain/atomistic
  imported: false
  recursive: false
  subsections: annotation_properties,data_properties,object_properties
GIT_REPOSITORY: emmo-repo/domain-atomistic
GIT_BASE_URL: github.com
REFERENCE_SUBSECTIONS: all
REFERENCE_IMPORTED: 'false'
REFERENCE_RECURSIVE: 'true'
REFERENCE_IRI_REGEX: None#
