name: Update GitHub Pages

on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
      - cd_update_pages

env:
  GIT_USER_NAME: EMMO Developers
  GIT_USER_EMAIL: "atomistic@emmc.eu"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug info
      run: |
        echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install ROBOT
      run: |
        mkdir bin
        wget -nv https://github.com/ontodev/robot/releases/download/v1.9.6/robot.jar
        mv robot.jar bin/.
        curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > bin/robot
        chmod +x bin/robot
        ls -l bin/

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install sphinx sphinxcontrib-globalsubs sphinx_design nbsphinx pydata-sphinx-theme
        pip install git+https://github.com/atomistic-repo/EMMOntoPy.git@master

    - name: Create and prepare build and public directories
      run: |
        mkdir build public
        if [ -d doc/_static ]; then cp -rf doc/_static/* build/. ; fi

    - name: Create ontologies for publishing
      run: |
        ontoconvert -sawe --base-iri="https://w3id.org/atomistic#" --iri=https://w3id.org/atomistic atomistic.ttl public/atomistic.ttl
        bin/robot reason --reasoner HermiT --input public/atomistic.ttl --output public/atomistic-inferred.ttl
        ontoconvert public/atomistic.ttl public/atomistic.owl
        ontoconvert public/atomistic-inferred.ttl public/atomistic-inferred.owl
        ontoconvert -saw --rename-iris --base-iri="https://w3id.org/atomistic#" --iri=https://w3id.org/atomistic atomistic.ttl public/atomistic-for-humans.ttl
        bin/robot reason --reasoner HermiT --input public/atomistic-for-humans.ttl --output public/atomistic-for-humans-inferred.ttl


    - name: Generate html documentation (based on atomistic)
      run: |
        ontodoc --iri-regex=https://w3id.org/atomistic atomistic.ttl build/atomistic.rst
        sphinx-build "build/" "public/"

    - name: Checkout GitHub Pages for EMMO-repo
      uses: actions/checkout@v4
      with:
        repository: atomistic-repo/atomistic-repo.github.io
        path: pages
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-strict: no

    - name: Copy to GitHub Pages
      run: |
        # Do not overwrite index.html
        rm public/index.html
        # Tell GitHub that this site is not generated with jekyll
        touch public/.nojekyll
        # Copy to latest (root)
        cp -rf public/* pages/.
        # Copy to version
        VERSION=$(git rev-parse --abbrev-ref HEAD)
      if [ ! -d pages/versions/${VERSION} ]; then \:q
          mkdir pages/versions/${VERSION}
        fi
        cp -rf public/* pages/versions/${VERSION}/.

      # Domain repositories can use peaceiris/actions-gh-pages@v3.
      # However, since EMMO for historical reasons uses a separate repo
      # for its GitHub Pages, it is easier to use git directly.
    - name: Push to GitHub Pages
      run: |
        cd pages
        git config --global user.email "atomistic@emmc.eu"
        git config --global user.name "EMMO Developer"
        git add --all
        if [ -n "$(git status --porcelain -uno)" ]; then \
          git commit -m 'Updated releasetable'; \
          git pull origin master; \
          git push origin master; \
        fi

